// Сгенерировано автоматически из Google Drive
const APPS = [
  {
    "name": "Учимся словам",
    "version": "1.0.0",
    "slug": "учимся-словам",
    "bundleId": "com.example.учимся-словам",
    "size": 285945630,
    "sizeFormatted": "272.7 МБ",
    "manifestUrl": "https://soundtrackminus-hash.github.io/ios-ota-apps-site/apps/учимся-словам/manifest.plist",
    "downloadUrl": "https://github.com/soundtrackminus-hash/ios-ota-apps-site/releases/download/учимся-словам-1.0.0/учимся-словам.ipa",
    "iconUrl": "icons/учимся-словам.png",
    "searchTags": "учимся словам"
  },
  {
    "name": "Spotluma",
    "version": "1.0.0",
    "slug": "spotluma",
    "bundleId": "com.example.spotluma",
    "size": 467140301,
    "sizeFormatted": "445.5 МБ",
    "manifestUrl": "https://soundtrackminus-hash.github.io/ios-ota-apps-site/apps/spotluma/manifest.plist",
    "downloadUrl": "https://github.com/soundtrackminus-hash/ios-ota-apps-site/releases/download/spotluma-1.0.0/spotluma.ipa",
    "iconUrl": "icons/spotluma.png",
    "searchTags": "spotluma"
  },
  {
    "name": "Atoy",
    "version": "1.0.0",
    "slug": "atoy",
    "bundleId": "com.example.atoy",
    "size": 94823278,
    "sizeFormatted": "90.4 МБ",
    "manifestUrl": "https://soundtrackminus-hash.github.io/ios-ota-apps-site/apps/atoy/manifest.plist",
    "downloadUrl": "https://github.com/soundtrackminus-hash/ios-ota-apps-site/releases/download/atoy-1.0.0/atoy.ipa",
    "iconUrl": "icons/atoy.png",
    "searchTags": "atoy"
  },
  {
    "name": "Ак Барс Онлайн",
    "version": "1.0.0",
    "slug": "ак-барс-онлайн",
    "bundleId": "com.example.ак-барс-онлайн",
    "size": 227422236,
    "sizeFormatted": "216.9 МБ",
    "manifestUrl": "https://soundtrackminus-hash.github.io/ios-ota-apps-site/apps/ак-барс-онлайн/manifest.plist",
    "downloadUrl": "https://github.com/soundtrackminus-hash/ios-ota-apps-site/releases/download/ак-барс-онлайн-1.0.0/ак-барс-онлайн.ipa",
    "iconUrl": "icons/ак-барс-онлайн.png",
    "searchTags": "ак барс онлайн"
  },
  {
    "name": "Без наличных MTC PAY",
    "version": "1.0.0",
    "slug": "без-наличных-mtc-pay",
    "bundleId": "com.example.без-наличных-mtc-pay",
    "size": 67489554,
    "sizeFormatted": "64.4 МБ",
    "manifestUrl": "https://soundtrackminus-hash.github.io/ios-ota-apps-site/apps/без-наличных-mtc-pay/manifest.plist",
    "downloadUrl": "https://github.com/soundtrackminus-hash/ios-ota-apps-site/releases/download/без-наличных-mtc-pay-1.0.0/без-наличных-mtc-pay.ipa",
    "iconUrl": "icons/без-наличных-mtc-pay.png",
    "searchTags": "без наличных mtc pay"
  },
  {
    "name": "Афина бюджет ПСБ БАНК",
    "version": "1.0.0",
    "slug": "афина-бюджет-псб-банк",
    "bundleId": "com.example.афина-бюджет-псб-банк",
    "size": 115301269,
    "sizeFormatted": "110.0 МБ",
    "manifestUrl": "https://soundtrackminus-hash.github.io/ios-ota-apps-site/apps/афина-бюджет-псб-банк/manifest.plist",
    "downloadUrl": "https://github.com/soundtrackminus-hash/ios-ota-apps-site/releases/download/афина-бюджет-псб-банк-1.0.0/афина-бюджет-псб-банк.ipa",
    "iconUrl": "icons/афина-бюджет-псб-банк.png",
    "searchTags": "афина бюджет псб банк"
  },
  {
    "name": "TEBOIL",
    "version": "1.0.0",
    "slug": "teboil",
    "bundleId": "com.example.teboil",
    "size": 89057882,
    "sizeFormatted": "84.9 МБ",
    "manifestUrl": "https://soundtrackminus-hash.github.io/ios-ota-apps-site/apps/teboil/manifest.plist",
    "downloadUrl": "https://github.com/soundtrackminus-hash/ios-ota-apps-site/releases/download/teboil-1.0.0/teboil.ipa",
    "iconUrl": "icons/teboil.png",
    "searchTags": "teboil"
  },
  {
    "name": "Делим Вместе АЛЬФА БАНК",
    "version": "1.0.0",
    "slug": "делим-вместе-альфа-банк",
    "bundleId": "com.example.делим-вместе-альфа-банк",
    "size": 421437678,
    "sizeFormatted": "401.9 МБ",
    "manifestUrl": "https://soundtrackminus-hash.github.io/ios-ota-apps-site/apps/делим-вместе-альфа-банк/manifest.plist",
    "downloadUrl": "https://github.com/soundtrackminus-hash/ios-ota-apps-site/releases/download/делим-вместе-альфа-банк-1.0.0/делим-вместе-альфа-банк.ipa",
    "iconUrl": "icons/делим-вместе-альфа-банк.png",
    "searchTags": "делим вместе альфа банк"
  },
  {
    "name": "iManager by INS INVEST ИНГОССТРАХ",
    "version": "1.0.0",
    "slug": "imanager-by-ins-invest-ингосстрах",
    "bundleId": "com.example.imanager-by-ins-invest-ингосстрах",
    "size": 228313258,
    "sizeFormatted": "217.7 МБ",
    "manifestUrl": "https://soundtrackminus-hash.github.io/ios-ota-apps-site/apps/imanager-by-ins-invest-ингосстрах/manifest.plist",
    "downloadUrl": "https://github.com/soundtrackminus-hash/ios-ota-apps-site/releases/download/imanager-by-ins-invest-ингосстрах-1.0.0/imanager-by-ins-invest-ингосстрах.ipa",
    "iconUrl": "icons/imanager-by-ins-invest-ингосстрах.png",
    "searchTags": "imanager by ins invest ингосстрах"
  },
  {
    "name": "Аукцион Au.ru АВИТО",
    "version": "1.0.0",
    "slug": "аукцион-au-ru-авито",
    "bundleId": "com.example.аукцион-au-ru-авито",
    "size": 579593641,
    "sizeFormatted": "552.7 МБ",
    "manifestUrl": "https://soundtrackminus-hash.github.io/ios-ota-apps-site/apps/аукцион-au-ru-авито/manifest.plist",
    "downloadUrl": "https://github.com/soundtrackminus-hash/ios-ota-apps-site/releases/download/аукцион-au-ru-авито-1.0.0/аукцион-au-ru-авито.ipa",
    "iconUrl": "icons/аукцион-au-ru-авито.png",
    "searchTags": "аукцион au ru авито"
  },
  {
    "name": "Anero_ ваш онлайн помощник АВИТО",
    "version": "1.0.0",
    "slug": "anero-ваш-онлайн-помощник-авито",
    "bundleId": "com.example.anero-ваш-онлайн-помощник-авито",
    "size": 549639432,
    "sizeFormatted": "524.2 МБ",
    "manifestUrl": "https://soundtrackminus-hash.github.io/ios-ota-apps-site/apps/anero-ваш-онлайн-помощник-авито/manifest.plist",
    "downloadUrl": "https://github.com/soundtrackminus-hash/ios-ota-apps-site/releases/download/anero-ваш-онлайн-помощник-авито-1.0.0/anero-ваш-онлайн-помощник-авито.ipa",
    "iconUrl": "icons/anero-ваш-онлайн-помощник-авито.png",
    "searchTags": "anero ваш онлайн помощник авито"
  },
  {
    "name": "Happ - Proxy Utility Plus",
    "version": "1.0.0",
    "slug": "happ-proxy-utility-plus",
    "bundleId": "com.example.happ-proxy-utility-plus",
    "size": 305142190,
    "sizeFormatted": "291.0 МБ",
    "manifestUrl": "https://soundtrackminus-hash.github.io/ios-ota-apps-site/apps/happ-proxy-utility-plus/manifest.plist",
    "downloadUrl": "https://github.com/soundtrackminus-hash/ios-ota-apps-site/releases/download/happ-proxy-utility-plus-1.0.0/happ-proxy-utility-plus.ipa",
    "iconUrl": "icons/happ-proxy-utility-plus.png",
    "searchTags": "happ proxy utility plus"
  },
  {
    "name": "Яндекс Сим",
    "version": "1.0.0",
    "slug": "яндекс-сим",
    "bundleId": "com.example.яндекс-сим",
    "size": 44521214,
    "sizeFormatted": "42.5 МБ",
    "manifestUrl": "https://soundtrackminus-hash.github.io/ios-ota-apps-site/apps/яндекс-сим/manifest.plist",
    "downloadUrl": "https://github.com/soundtrackminus-hash/ios-ota-apps-site/releases/download/яндекс-сим-1.0.0/яндекс-сим.ipa",
    "iconUrl": "icons/яндекс-сим.png",
    "searchTags": "яндекс сим"
  },
  {
    "name": "SpeakaBoo СБЕРКИДС",
    "version": "1.0.0",
    "slug": "speakaboo-сберкидс",
    "bundleId": "com.example.speakaboo-сберкидс",
    "size": 189685581,
    "sizeFormatted": "180.9 МБ",
    "manifestUrl": "https://soundtrackminus-hash.github.io/ios-ota-apps-site/apps/speakaboo-сберкидс/manifest.plist",
    "downloadUrl": "https://github.com/soundtrackminus-hash/ios-ota-apps-site/releases/download/speakaboo-сберкидс-1.0.0/speakaboo-сберкидс.ipa",
    "iconUrl": "icons/speakaboo-сберкидс.png",
    "searchTags": "speakaboo сберкидс"
  },
  {
    "name": "FuellnTime ТБАНК ИНВЕСТИЦИИ",
    "version": "1.0.0",
    "slug": "fuellntime-тбанк-инвестиции",
    "bundleId": "com.example.fuellntime-тбанк-инвестиции",
    "size": 218825843,
    "sizeFormatted": "208.7 МБ",
    "manifestUrl": "https://soundtrackminus-hash.github.io/ios-ota-apps-site/apps/fuellntime-тбанк-инвестиции/manifest.plist",
    "downloadUrl": "https://github.com/soundtrackminus-hash/ios-ota-apps-site/releases/download/fuellntime-тбанк-инвестиции-1.0.0/fuellntime-тбанк-инвестиции.ipa",
    "iconUrl": "icons/fuellntime-тбанк-инвестиции.png",
    "searchTags": "fuellntime тбанк инвестиции"
  },
  {
    "name": "SCB Notes СОВКОМБАНК",
    "version": "1.0.0",
    "slug": "scb-notes-совкомбанк",
    "bundleId": "com.example.scb-notes-совкомбанк",
    "size": 115856662,
    "sizeFormatted": "110.5 МБ",
    "manifestUrl": "https://soundtrackminus-hash.github.io/ios-ota-apps-site/apps/scb-notes-совкомбанк/manifest.plist",
    "downloadUrl": "https://github.com/soundtrackminus-hash/ios-ota-apps-site/releases/download/scb-notes-совкомбанк-1.0.0/scb-notes-совкомбанк.ipa",
    "iconUrl": "icons/scb-notes-совкомбанк.png",
    "searchTags": "scb notes совкомбанк"
  },
  {
    "name": "Мобио СБЕРМОБАЙЛ",
    "version": "1.0.0",
    "slug": "мобио-сбермобайл",
    "bundleId": "com.example.мобио-сбермобайл",
    "size": 56725456,
    "sizeFormatted": "54.1 МБ",
    "manifestUrl": "https://soundtrackminus-hash.github.io/ios-ota-apps-site/apps/мобио-сбермобайл/manifest.plist",
    "downloadUrl": "https://github.com/soundtrackminus-hash/ios-ota-apps-site/releases/download/мобио-сбермобайл-1.0.0/мобио-сбермобайл.ipa",
    "iconUrl": "icons/hz-poster.svg",
    "searchTags": "мобио сбермобайл"
  },
  {
    "name": "PianoWave ПРЕМЬЕР КИНОТЕАТР",
    "version": "1.0.0",
    "slug": "pianowave-премьер-кинотеатр",
    "bundleId": "com.example.pianowave-премьер-кинотеатр",
    "size": 71579491,
    "sizeFormatted": "68.3 МБ",
    "manifestUrl": "https://soundtrackminus-hash.github.io/ios-ota-apps-site/apps/pianowave-премьер-кинотеатр/manifest.plist",
    "downloadUrl": "https://github.com/soundtrackminus-hash/ios-ota-apps-site/releases/download/pianowave-премьер-кинотеатр-1.0.0/pianowave-премьер-кинотеатр.ipa",
    "iconUrl": "icons/pianowave-премьер-кинотеатр.png",
    "searchTags": "pianowave премьер кинотеатр"
  },
  {
    "name": "incy",
    "version": "1.0.0",
    "slug": "incy",
    "bundleId": "com.example.incy",
    "size": 134143600,
    "sizeFormatted": "127.9 МБ",
    "manifestUrl": "https://soundtrackminus-hash.github.io/ios-ota-apps-site/apps/incy/manifest.plist",
    "downloadUrl": "https://github.com/soundtrackminus-hash/ios-ota-apps-site/releases/download/incy-1.0.0/incy.ipa",
    "iconUrl": "icons/incy.png",
    "searchTags": "incy"
  },
  {
    "name": "Здоровье и страхование СОГАЗ",
    "version": "1.0.0",
    "slug": "здоровье-и-страхование-согаз",
    "bundleId": "com.example.здоровье-и-страхование-согаз",
    "size": 99047846,
    "sizeFormatted": "94.5 МБ",
    "manifestUrl": "https://soundtrackminus-hash.github.io/ios-ota-apps-site/apps/здоровье-и-страхование-согаз/manifest.plist",
    "downloadUrl": "https://github.com/soundtrackminus-hash/ios-ota-apps-site/releases/download/здоровье-и-страхование-согаз-1.0.0/здоровье-и-страхование-согаз.ipa",
    "iconUrl": "icons/здоровье-и-страхование-согаз.png",
    "searchTags": "здоровье и страхование согаз"
  },
  {
    "name": "GetQuot ВТБ ИНВЕСТИЦИИ",
    "version": "1.0.0",
    "slug": "getquot-втб-инвестиции",
    "bundleId": "com.example.getquot-втб-инвестиции",
    "size": 142570252,
    "sizeFormatted": "136.0 МБ",
    "manifestUrl": "https://soundtrackminus-hash.github.io/ios-ota-apps-site/apps/getquot-втб-инвестиции/manifest.plist",
    "downloadUrl": "https://github.com/soundtrackminus-hash/ios-ota-apps-site/releases/download/getquot-втб-инвестиции-1.0.0/getquot-втб-инвестиции.ipa",
    "iconUrl": "icons/getquot-втб-инвестиции.png",
    "searchTags": "getquot втб инвестиции"
  },
  {
    "name": "Solar_ Sun Compass СБЕР ИНВЕСТИЦИИ",
    "version": "1.0.0",
    "slug": "solar-sun-compass-сбер-инвестиции",
    "bundleId": "com.example.solar-sun-compass-сбер-инвестиции",
    "size": 174724320,
    "sizeFormatted": "166.6 МБ",
    "manifestUrl": "https://soundtrackminus-hash.github.io/ios-ota-apps-site/apps/solar-sun-compass-сбер-инвестиции/manifest.plist",
    "downloadUrl": "https://github.com/soundtrackminus-hash/ios-ota-apps-site/releases/download/solar-sun-compass-сбер-инвестиции-1.0.0/solar-sun-compass-сбер-инвестиции.ipa",
    "iconUrl": "icons/solar-sun-compass-сбер-инвестиции.png",
    "searchTags": "solar sun compass сбер инвестиции"
  },
  {
    "name": "Craftersy ТБАНК",
    "version": "1.0.0",
    "slug": "craftersy-тбанк",
    "bundleId": "com.example.craftersy-тбанк",
    "size": 496809218,
    "sizeFormatted": "473.8 МБ",
    "manifestUrl": "https://soundtrackminus-hash.github.io/ios-ota-apps-site/apps/craftersy-тбанк/manifest.plist",
    "downloadUrl": "https://github.com/soundtrackminus-hash/ios-ota-apps-site/releases/download/craftersy-тбанк-1.0.0/craftersy-тбанк.ipa",
    "iconUrl": "icons/hz-poster.svg",
    "searchTags": "craftersy тбанк"
  }
  {
    "name": "СберБанк",
    "version": "17.6.1",
    "slug": "сбербанк-online",
    "bundleId": "com.inv.gen",
    "size": 532018407,
    "sizeFormatted": "507.4 МБ",
    "manifestUrl": "https://soundtrackminus-hash.github.io/ios-ota-apps-site/apps/сбербанк-online/manifest.plist",
    "downloadUrl": "https://github.com/soundtrackminus-hash/ios-ota-apps-site/releases/download/online-com-inv-gen-17.6.1/online-com-inv-gen.ipa",
    "iconUrl": "icons/сбербанк.png",
    "searchTags": "сбер банк онлайн"
  },
];
