// Сгенерировано из apps/*/manifest.plist: только приложения со скачиваемым IPA
const APPS = [
  {
    "name": "Anero",
    "version": "1786539266",
    "slug": "anero-ваш-онлайн-помощник-авито",
    "bundleId": "online.anero.app",
    "size": 549639432,
    "sizeFormatted": "524.2 МБ",
    "manifestUrl": "https://soundtrackminus-hash.github.io/ios-ota-apps-site/apps/anero-ваш-онлайн-помощник-авито/manifest.plist",
    "downloadUrl": "https://github.com/soundtrackminus-hash/ios-ota-apps-site/releases/download/anero-%D0%B2%D0%B0%D1%88-%D0%BE%D0%BD%D0%BB%D0%B0%D0%B9%D0%BD-%D0%BF%D0%BE%D0%BC%D0%BE%D1%89%D0%BD%D0%B8%D0%BA-%D0%B0%D0%B2%D0%B8%D1%82%D0%BE-1.0.0/anero-.-.-.-.ipa",
    "iconUrl": "icons/anero-ваш-онлайн-помощник-авито.png",
    "searchTags": "anero"
  },
  {
    "name": "ATOY",
    "version": "15",
    "slug": "atoy",
    "bundleId": "ru.atoy.selfcare",
    "size": 94823278,
    "sizeFormatted": "90.4 МБ",
    "manifestUrl": "https://soundtrackminus-hash.github.io/ios-ota-apps-site/apps/atoy/manifest.plist",
    "downloadUrl": "https://github.com/soundtrackminus-hash/ios-ota-apps-site/releases/download/atoy-1.0.0/atoy.ipa",
    "iconUrl": "icons/atoy.png",
    "searchTags": "atoy"
  },
  {
    "name": "Au",
    "version": "224.0",
    "slug": "au",
    "bundleId": "org.reactjs.native.prod.AuReactNativeApp",
    "size": 579593641,
    "sizeFormatted": "552.7 МБ",
    "manifestUrl": "https://soundtrackminus-hash.github.io/ios-ota-apps-site/apps/au/manifest.plist",
    "downloadUrl": "https://github.com/soundtrackminus-hash/ios-ota-apps-site/releases/download/au-224.0/au.ipa",
    "iconUrl": "icons/hz-poster.svg",
    "searchTags": "au"
  },
  {
    "name": "Craftersy",
    "version": "5.1",
    "slug": "craftersy",
    "bundleId": "apps.homepreserves.prohome",
    "size": 496809218,
    "sizeFormatted": "473.8 МБ",
    "manifestUrl": "https://soundtrackminus-hash.github.io/ios-ota-apps-site/apps/craftersy/manifest.plist",
    "downloadUrl": "https://github.com/soundtrackminus-hash/ios-ota-apps-site/releases/download/craftersy-5.1/craftersy.ipa",
    "iconUrl": "icons/hz-poster.svg",
    "searchTags": "craftersy"
  },
  {
    "name": "FileHub",
    "version": "10.3.5",
    "slug": "filehub",
    "bundleId": "com.imoreapps.portabledisk",
    "size": 63460607,
    "sizeFormatted": "60.5 МБ",
    "manifestUrl": "https://soundtrackminus-hash.github.io/ios-ota-apps-site/apps/filehub/manifest.plist",
    "downloadUrl": "https://github.com/soundtrackminus-hash/ios-ota-apps-site/releases/download/filehub-10.3.5/filehub.ipa",
    "iconUrl": "icons/hz-poster.svg",
    "searchTags": "filehub"
  },
  {
    "name": "FuelInTime",
    "version": "1.3",
    "slug": "fuelintime",
    "bundleId": "com.ivars.fueltime",
    "size": 218825843,
    "sizeFormatted": "208.7 МБ",
    "manifestUrl": "https://soundtrackminus-hash.github.io/ios-ota-apps-site/apps/fuelintime/manifest.plist",
    "downloadUrl": "https://github.com/soundtrackminus-hash/ios-ota-apps-site/releases/download/fuelintime-1.3/fuelintime.ipa",
    "iconUrl": "icons/hz-poster.svg",
    "searchTags": "fuelintime"
  },
  {
    "name": "GetQuot",
    "version": "2.0.0",
    "slug": "getquot",
    "bundleId": "pro.smartitservices.getquote",
    "size": 142570252,
    "sizeFormatted": "136.0 МБ",
    "manifestUrl": "https://soundtrackminus-hash.github.io/ios-ota-apps-site/apps/getquot/manifest.plist",
    "downloadUrl": "https://github.com/soundtrackminus-hash/ios-ota-apps-site/releases/download/getquot-2.0.0/getquot.ipa",
    "iconUrl": "icons/hz-poster.svg",
    "searchTags": "getquot"
  },
  {
    "name": "GTA III",
    "version": "1.3.13",
    "slug": "gta-iii",
    "bundleId": "com.rockstargames.gta3ios",
    "size": 490095254,
    "sizeFormatted": "467.4 МБ",
    "manifestUrl": "https://soundtrackminus-hash.github.io/ios-ota-apps-site/apps/gta-iii/manifest.plist",
    "downloadUrl": "https://github.com/soundtrackminus-hash/ios-ota-apps-site/releases/download/gta-iii-1.3.13/gta-iii.ipa",
    "iconUrl": "icons/hz-poster.svg",
    "searchTags": "gta iii"
  },
  {
    "name": "GTA: SA",
    "version": "2.2.21",
    "slug": "gta-sa",
    "bundleId": "com.rockstargames.gta3sa",
    "size": 1933511605,
    "sizeFormatted": "1843.9 МБ",
    "manifestUrl": "https://soundtrackminus-hash.github.io/ios-ota-apps-site/apps/gta-sa/manifest.plist",
    "downloadUrl": "https://github.com/soundtrackminus-hash/ios-ota-apps-site/releases/download/gta-sa-2.2.21/GTA_SA_2.2.21.ipa",
    "iconUrl": "icons/gta-sa.png",
    "searchTags": "gta: sa"
  },
  {
    "name": "Happ Plus",
    "version": "2607291116",
    "slug": "happ-proxy-utility-plus",
    "bundleId": "su.ffg.happ.ruplus2",
    "size": 305142190,
    "sizeFormatted": "291.0 МБ",
    "manifestUrl": "https://soundtrackminus-hash.github.io/ios-ota-apps-site/apps/happ-proxy-utility-plus/manifest.plist",
    "downloadUrl": "https://github.com/soundtrackminus-hash/ios-ota-apps-site/releases/download/happ-proxy-utility-plus-1.0.0/happ-proxy-utility-plus.ipa",
    "iconUrl": "icons/happ-proxy-utility-plus.png",
    "searchTags": "happ plus"
  },
  {
    "name": "iManager",
    "version": "1.11",
    "slug": "imanager",
    "bundleId": "am.invest.imanager",
    "size": 228313258,
    "sizeFormatted": "217.7 МБ",
    "manifestUrl": "https://soundtrackminus-hash.github.io/ios-ota-apps-site/apps/imanager/manifest.plist",
    "downloadUrl": "https://github.com/soundtrackminus-hash/ios-ota-apps-site/releases/download/imanager-1.11/imanager.ipa",
    "iconUrl": "icons/hz-poster.svg",
    "searchTags": "imanager"
  },
  {
    "name": "INCY",
    "version": "2109260730",
    "slug": "incy",
    "bundleId": "llc.itdev.incy",
    "size": 134143600,
    "sizeFormatted": "127.9 МБ",
    "manifestUrl": "https://soundtrackminus-hash.github.io/ios-ota-apps-site/apps/incy/manifest.plist",
    "downloadUrl": "https://github.com/soundtrackminus-hash/ios-ota-apps-site/releases/download/incy-1.0.0/incy.ipa",
    "iconUrl": "icons/incy.png",
    "searchTags": "incy"
  },
  {
    "name": "Infinity Blade",
    "version": "1.4.3",
    "slug": "infinity-blade",
    "bundleId": "com.chairentertainment.birthright",
    "size": 630229757,
    "sizeFormatted": "601.0 МБ",
    "manifestUrl": "https://soundtrackminus-hash.github.io/ios-ota-apps-site/apps/infinity-blade/manifest.plist",
    "downloadUrl": "https://github.com/soundtrackminus-hash/ios-ota-apps-site/releases/download/infinity-blade-1.4.3/infinity-blade.ipa",
    "iconUrl": "icons/hz-poster.svg",
    "searchTags": "infinity blade"
  },
  {
    "name": "MAX",
    "version": "26.17.3",
    "slug": "max",
    "bundleId": "ru.oneme.app",
    "size": 90917202,
    "sizeFormatted": "86.7 МБ",
    "manifestUrl": "https://soundtrackminus-hash.github.io/ios-ota-apps-site/apps/max/manifest.plist",
    "downloadUrl": "https://github.com/soundtrackminus-hash/ios-ota-apps-site/releases/download/max-26.17.3/max.ipa",
    "iconUrl": "icons/hz-poster.svg",
    "searchTags": "max"
  },
  {
    "name": "Most Wanted",
    "version": "1.1.3",
    "slug": "most-wanted",
    "bundleId": "com.ea.nfs13.bv",
    "size": 722222842,
    "sizeFormatted": "688.8 МБ",
    "manifestUrl": "https://soundtrackminus-hash.github.io/ios-ota-apps-site/apps/most-wanted/manifest.plist",
    "downloadUrl": "https://github.com/soundtrackminus-hash/ios-ota-apps-site/releases/download/most-wanted-1.1.3/most-wanted.ipa",
    "iconUrl": "icons/hz-poster.svg",
    "searchTags": "most wanted"
  },
  {
    "name": "Notion",
    "version": "0.4.2220",
    "slug": "notion",
    "bundleId": "notion.id",
    "size": 354200079,
    "sizeFormatted": "337.8 МБ",
    "manifestUrl": "https://soundtrackminus-hash.github.io/ios-ota-apps-site/apps/notion/manifest.plist",
    "downloadUrl": "https://github.com/soundtrackminus-hash/ios-ota-apps-site/releases/download/notion-0.4.2220/notion.ipa",
    "iconUrl": "icons/hz-poster.svg",
    "searchTags": "notion"
  },
  {
    "name": "OK",
    "version": "11.63.1",
    "slug": "ok",
    "bundleId": "ru.odnoklassniki.iphone",
    "size": 331444025,
    "sizeFormatted": "316.1 МБ",
    "manifestUrl": "https://soundtrackminus-hash.github.io/ios-ota-apps-site/apps/ok/manifest.plist",
    "downloadUrl": "https://github.com/soundtrackminus-hash/ios-ota-apps-site/releases/download/ok-11.63.1/ok.ipa",
    "iconUrl": "icons/hz-poster.svg",
    "searchTags": "ok"
  },
  {
    "name": "Online 17.6.1 СБЕРБАНК",
    "version": "17.6.1",
    "slug": "online-17-6-1-sberbank",
    "bundleId": "com.inv.gen",
    "size": 476143616,
    "sizeFormatted": "454.1 МБ",
    "manifestUrl": "https://soundtrackminus-hash.github.io/ios-ota-apps-site/apps/online-17-6-1-sberbank/manifest.plist",
    "downloadUrl": "https://github.com/soundtrackminus-hash/ios-ota-apps-site/releases/download/online-17-6-1-sberbank-1.0.0/Online-17.6.1-.ipa",
    "iconUrl": "icons/online-17-6-1-sberbank.png",
    "searchTags": "online 17.6.1 сбербанк"
  },
  {
    "name": "PianoWave",
    "version": "1.2.0",
    "slug": "pianowave",
    "bundleId": "com.pianowave.musicgame",
    "size": 71579491,
    "sizeFormatted": "68.3 МБ",
    "manifestUrl": "https://soundtrackminus-hash.github.io/ios-ota-apps-site/apps/pianowave/manifest.plist",
    "downloadUrl": "https://github.com/soundtrackminus-hash/ios-ota-apps-site/releases/download/pianowave-1.2.0/pianowave.ipa",
    "iconUrl": "icons/hz-poster.svg",
    "searchTags": "pianowave"
  },
  {
    "name": "Real Racing 2",
    "version": "1.13.50",
    "slug": "real-racing-2",
    "bundleId": "com.firemint.realracing2",
    "size": 448988227,
    "sizeFormatted": "428.2 МБ",
    "manifestUrl": "https://soundtrackminus-hash.github.io/ios-ota-apps-site/apps/real-racing-2/manifest.plist",
    "downloadUrl": "https://github.com/soundtrackminus-hash/ios-ota-apps-site/releases/download/real-racing-2-1.13.50/racing2.ipa",
    "iconUrl": "icons/real-racing-2.png",
    "searchTags": "real racing 2"
  },
  {
    "name": "Relaxia",
    "version": "2.6",
    "slug": "relaxia",
    "bundleId": "com.payIX.RelaxToSleepPaid",
    "size": 82996179,
    "sizeFormatted": "79.2 МБ",
    "manifestUrl": "https://soundtrackminus-hash.github.io/ios-ota-apps-site/apps/relaxia/manifest.plist",
    "downloadUrl": "https://github.com/soundtrackminus-hash/ios-ota-apps-site/releases/download/relaxia-2.6/relaxia.ipa",
    "iconUrl": "icons/hz-poster.svg",
    "searchTags": "relaxia"
  },
  {
    "name": "SCB Notes",
    "version": "1.1",
    "slug": "scb-notes",
    "bundleId": "org.mydiary",
    "size": 115856662,
    "sizeFormatted": "110.5 МБ",
    "manifestUrl": "https://soundtrackminus-hash.github.io/ios-ota-apps-site/apps/scb-notes/manifest.plist",
    "downloadUrl": "https://github.com/soundtrackminus-hash/ios-ota-apps-site/releases/download/scb-notes-1.1/scb-notes.ipa",
    "iconUrl": "icons/hz-poster.svg",
    "searchTags": "scb notes"
  },
  {
    "name": "SilentFund",
    "version": "1.3.1",
    "slug": "silentfund",
    "bundleId": "com.silentmap.app",
    "size": 217588890,
    "sizeFormatted": "207.5 МБ",
    "manifestUrl": "https://soundtrackminus-hash.github.io/ios-ota-apps-site/apps/silentfund/manifest.plist",
    "downloadUrl": "https://github.com/soundtrackminus-hash/ios-ota-apps-site/releases/download/silentfund-1.3.1/silentfund.ipa",
    "iconUrl": "icons/hz-poster.svg",
    "searchTags": "silentfund"
  },
  {
    "name": "SlicingDices",
    "version": "1.2.1",
    "slug": "slicingdices",
    "bundleId": "com.slicingdice.game",
    "size": 58238466,
    "sizeFormatted": "55.5 МБ",
    "manifestUrl": "https://soundtrackminus-hash.github.io/ios-ota-apps-site/apps/slicingdices/manifest.plist",
    "downloadUrl": "https://github.com/soundtrackminus-hash/ios-ota-apps-site/releases/download/slicingdices-1.2.1/slicingdices.ipa",
    "iconUrl": "icons/hz-poster.svg",
    "searchTags": "slicingdices"
  },
  {
    "name": "SpeakaBoo",
    "version": "2.1",
    "slug": "speakaboo",
    "bundleId": "app.speakaboo.com",
    "size": 189685581,
    "sizeFormatted": "180.9 МБ",
    "manifestUrl": "https://soundtrackminus-hash.github.io/ios-ota-apps-site/apps/speakaboo/manifest.plist",
    "downloadUrl": "https://github.com/soundtrackminus-hash/ios-ota-apps-site/releases/download/speakaboo-2.1/speakaboo.ipa",
    "iconUrl": "icons/hz-poster.svg",
    "searchTags": "speakaboo"
  },
  {
    "name": "SplitActivities",
    "version": "28052025.3",
    "slug": "splitactivities",
    "bundleId": "com.splitactivities.app",
    "size": 421437678,
    "sizeFormatted": "401.9 МБ",
    "manifestUrl": "https://soundtrackminus-hash.github.io/ios-ota-apps-site/apps/splitactivities/manifest.plist",
    "downloadUrl": "https://github.com/soundtrackminus-hash/ios-ota-apps-site/releases/download/splitactivities-28052025.3/splitactivities.ipa",
    "iconUrl": "icons/hz-poster.svg",
    "searchTags": "splitactivities"
  },
  {
    "name": "Spotluma",
    "version": "2",
    "slug": "spotluma",
    "bundleId": "app.cleanorder.hudorban",
    "size": 467140301,
    "sizeFormatted": "445.5 МБ",
    "manifestUrl": "https://soundtrackminus-hash.github.io/ios-ota-apps-site/apps/spotluma/manifest.plist",
    "downloadUrl": "https://github.com/soundtrackminus-hash/ios-ota-apps-site/releases/download/spotluma-1.0.0/spotluma.ipa",
    "iconUrl": "icons/spotluma.png",
    "searchTags": "spotluma"
  },
  {
    "name": "Teboil",
    "version": "266",
    "slug": "teboil",
    "bundleId": "com.teboil.azs",
    "size": 89057882,
    "sizeFormatted": "84.9 МБ",
    "manifestUrl": "https://soundtrackminus-hash.github.io/ios-ota-apps-site/apps/teboil/manifest.plist",
    "downloadUrl": "https://github.com/soundtrackminus-hash/ios-ota-apps-site/releases/download/teboil-1.0.0/teboil.ipa",
    "iconUrl": "icons/teboil.png",
    "searchTags": "teboil"
  },
  {
    "name": "Toast",
    "version": "2.0.1",
    "slug": "toast",
    "bundleId": "com.toastmaster.app",
    "size": 452158746,
    "sizeFormatted": "431.2 МБ",
    "manifestUrl": "https://soundtrackminus-hash.github.io/ios-ota-apps-site/apps/toast/manifest.plist",
    "downloadUrl": "https://github.com/soundtrackminus-hash/ios-ota-apps-site/releases/download/toast-2.0.1/toast.ipa",
    "iconUrl": "icons/hz-poster.svg",
    "searchTags": "toast"
  },
  {
    "name": "VK",
    "version": "8.183.1",
    "slug": "vk",
    "bundleId": "com.vk.vkclient",
    "size": 437223900,
    "sizeFormatted": "417.0 МБ",
    "manifestUrl": "https://soundtrackminus-hash.github.io/ios-ota-apps-site/apps/vk/manifest.plist",
    "downloadUrl": "https://github.com/soundtrackminus-hash/ios-ota-apps-site/releases/download/vk-8.183.1/vk.ipa",
    "iconUrl": "icons/hz-poster.svg",
    "searchTags": "vk"
  },
  {
    "name": "VK Music",
    "version": "8.30.1",
    "slug": "vk-music",
    "bundleId": "com.music.vk",
    "size": 189100192,
    "sizeFormatted": "180.3 МБ",
    "manifestUrl": "https://soundtrackminus-hash.github.io/ios-ota-apps-site/apps/vk-music/manifest.plist",
    "downloadUrl": "https://github.com/soundtrackminus-hash/ios-ota-apps-site/releases/download/vk-music-8.30.1/vk-music.ipa",
    "iconUrl": "icons/hz-poster.svg",
    "searchTags": "vk music"
  },
  {
    "name": "VK Video",
    "version": "8.183",
    "slug": "vk-video",
    "bundleId": "com.vk.vkvideo.prod",
    "size": 247521585,
    "sizeFormatted": "236.1 МБ",
    "manifestUrl": "https://soundtrackminus-hash.github.io/ios-ota-apps-site/apps/vk-video/manifest.plist",
    "downloadUrl": "https://github.com/soundtrackminus-hash/ios-ota-apps-site/releases/download/vk-video-8.183/vk-video.ipa",
    "iconUrl": "icons/hz-poster.svg",
    "searchTags": "vk video"
  },
  {
    "name": "Авито",
    "version": "200.5",
    "slug": "avito",
    "bundleId": "ru.avito.app",
    "size": 843682990,
    "sizeFormatted": "804.6 МБ",
    "manifestUrl": "https://soundtrackminus-hash.github.io/ios-ota-apps-site/apps/avito/manifest.plist",
    "downloadUrl": "https://github.com/soundtrackminus-hash/ios-ota-apps-site/releases/download/avito-200.5/avito.ipa",
    "iconUrl": "icons/hz-poster.svg",
    "searchTags": "авито"
  },
  {
    "name": "Автотека",
    "version": "2.5.3",
    "slug": "avtoteka",
    "bundleId": "ru.abd.autoteka.application",
    "size": 190916836,
    "sizeFormatted": "182.1 МБ",
    "manifestUrl": "https://soundtrackminus-hash.github.io/ios-ota-apps-site/apps/avtoteka/manifest.plist",
    "downloadUrl": "https://github.com/soundtrackminus-hash/ios-ota-apps-site/releases/download/avtoteka-2.5.3/avtoteka.ipa",
    "iconUrl": "icons/hz-poster.svg",
    "searchTags": "автотека"
  },
  {
    "name": "Ак Барс Банк",
    "version": "4837",
    "slug": "ak-bars-onlayn",
    "bundleId": "ru.abb.akbarsonline",
    "size": 227422236,
    "sizeFormatted": "216.9 МБ",
    "manifestUrl": "https://soundtrackminus-hash.github.io/ios-ota-apps-site/apps/ak-bars-onlayn/manifest.plist",
    "downloadUrl": "https://github.com/soundtrackminus-hash/ios-ota-apps-site/releases/download/ak-bars-onlayn-1.0.0/-.-.ipa",
    "iconUrl": "icons/ak-bars-onlayn.png",
    "searchTags": "ак барс банк"
  },
  {
    "name": "Афина бюджет",
    "version": "3",
    "slug": "afina-byudzhet-psb-bank",
    "bundleId": "uz.svoybyudzhet",
    "size": 115301269,
    "sizeFormatted": "110.0 МБ",
    "manifestUrl": "https://soundtrackminus-hash.github.io/ios-ota-apps-site/apps/afina-byudzhet-psb-bank/manifest.plist",
    "downloadUrl": "https://github.com/soundtrackminus-hash/ios-ota-apps-site/releases/download/afina-byudzhet-psb-bank-1.0.0/-.-.-.ipa",
    "iconUrl": "icons/afina-byudzhet-psb-bank.png",
    "searchTags": "афина бюджет"
  },
  {
    "name": "Бак+Бонус",
    "version": "1.1.1",
    "slug": "bak-bonus",
    "bundleId": "ru.bakbonus.appstarter",
    "size": 108116598,
    "sizeFormatted": "103.1 МБ",
    "manifestUrl": "https://soundtrackminus-hash.github.io/ios-ota-apps-site/apps/bak-bonus/manifest.plist",
    "downloadUrl": "https://github.com/soundtrackminus-hash/ios-ota-apps-site/releases/download/bak-bonus-1.1.1/bak-bonus.ipa",
    "iconUrl": "icons/hz-poster.svg",
    "searchTags": "бак+бонус"
  },
  {
    "name": "Без наличных",
    "version": "3.3.72",
    "slug": "bez-nalichnyh-mtc-pay",
    "bundleId": "ru.stream.pay",
    "size": 67489554,
    "sizeFormatted": "64.4 МБ",
    "manifestUrl": "https://soundtrackminus-hash.github.io/ios-ota-apps-site/apps/bez-nalichnyh-mtc-pay/manifest.plist",
    "downloadUrl": "https://github.com/soundtrackminus-hash/ios-ota-apps-site/releases/download/bez-nalichnyh-mtc-pay-1.0.0/-.-mtc-pay.ipa",
    "iconUrl": "icons/bez-nalichnyh-mtc-pay.png",
    "searchTags": "без наличных"
  },
  {
    "name": "До вершины",
    "version": "5.6.0",
    "slug": "do-vershiny",
    "bundleId": "ru.to.the.top.story.prod",
    "size": 438965631,
    "sizeFormatted": "418.6 МБ",
    "manifestUrl": "https://soundtrackminus-hash.github.io/ios-ota-apps-site/apps/do-vershiny/manifest.plist",
    "downloadUrl": "https://github.com/soundtrackminus-hash/ios-ota-apps-site/releases/download/do-vershiny-5.6.0/do-vershiny.ipa",
    "iconUrl": "icons/hz-poster.svg",
    "searchTags": "до вершины"
  },
  {
    "name": "Дом йоги",
    "version": "10.0.0",
    "slug": "dom-yogi",
    "bundleId": "yoga.appstore",
    "size": 579314857,
    "sizeFormatted": "552.5 МБ",
    "manifestUrl": "https://soundtrackminus-hash.github.io/ios-ota-apps-site/apps/dom-yogi/manifest.plist",
    "downloadUrl": "https://github.com/soundtrackminus-hash/ios-ota-apps-site/releases/download/dom-yogi-10.0.0/dom-yogi.ipa",
    "iconUrl": "icons/hz-poster.svg",
    "searchTags": "дом йоги"
  },
  {
    "name": "Здоровье",
    "version": "3.13.2",
    "slug": "zdorove",
    "bundleId": "kz.origon.empapp",
    "size": 99047846,
    "sizeFormatted": "94.5 МБ",
    "manifestUrl": "https://soundtrackminus-hash.github.io/ios-ota-apps-site/apps/zdorove/manifest.plist",
    "downloadUrl": "https://github.com/soundtrackminus-hash/ios-ota-apps-site/releases/download/zdorove-3.13.2/zdorove.ipa",
    "iconUrl": "icons/hz-poster.svg",
    "searchTags": "здоровье"
  },
  {
    "name": "Легко",
    "version": "6.89.0",
    "slug": "legko",
    "bundleId": "com.timofeykozuylichev.legko",
    "size": 314705412,
    "sizeFormatted": "300.1 МБ",
    "manifestUrl": "https://soundtrackminus-hash.github.io/ios-ota-apps-site/apps/legko/manifest.plist",
    "downloadUrl": "https://github.com/soundtrackminus-hash/ios-ota-apps-site/releases/download/legko-6.89.0/legko.ipa",
    "iconUrl": "icons/hz-poster.svg",
    "searchTags": "легко"
  },
  {
    "name": "Лента",
    "version": "6.81.0",
    "slug": "lenta",
    "bundleId": "com.icemobile.lenta",
    "size": 342100907,
    "sizeFormatted": "326.3 МБ",
    "manifestUrl": "https://soundtrackminus-hash.github.io/ios-ota-apps-site/apps/lenta/manifest.plist",
    "downloadUrl": "https://github.com/soundtrackminus-hash/ios-ota-apps-site/releases/download/lenta-6.81.0/lenta.ipa",
    "iconUrl": "icons/hz-poster.svg",
    "searchTags": "лента"
  },
  {
    "name": "Мобио",
    "version": "1.0.2",
    "slug": "mobio",
    "bundleId": "ru.tele-tie.app",
    "size": 56725456,
    "sizeFormatted": "54.1 МБ",
    "manifestUrl": "https://soundtrackminus-hash.github.io/ios-ota-apps-site/apps/mobio/manifest.plist",
    "downloadUrl": "https://github.com/soundtrackminus-hash/ios-ota-apps-site/releases/download/mobio-1.0.2/mobio.ipa",
    "iconUrl": "icons/hz-poster.svg",
    "searchTags": "мобио"
  },
  {
    "name": "Почта Mail.ru",
    "version": "15.92.0",
    "slug": "pochta-mail-ru",
    "bundleId": "ru.mail.mail",
    "size": 574547436,
    "sizeFormatted": "547.9 МБ",
    "manifestUrl": "https://soundtrackminus-hash.github.io/ios-ota-apps-site/apps/pochta-mail-ru/manifest.plist",
    "downloadUrl": "https://github.com/soundtrackminus-hash/ios-ota-apps-site/releases/download/pochta-mail-ru-15.92.0/pochta-mail-ru.ipa",
    "iconUrl": "icons/hz-poster.svg",
    "searchTags": "почта mail.ru"
  },
  {
    "name": "СберБанк",
    "version": "17.6.1",
    "slug": "сбербанк-online",
    "bundleId": "com.inv.gen",
    "size": 532018407,
    "sizeFormatted": "507.4 МБ",
    "manifestUrl": "https://soundtrackminus-hash.github.io/ios-ota-apps-site/apps/сбербанк-online/manifest.plist",
    "downloadUrl": "https://github.com/soundtrackminus-hash/ios-ota-apps-site/releases/download/online-com-inv-gen-17.6.1/online-com-inv-gen.ipa",
    "iconUrl": "icons/сбербанк.png",
    "searchTags": "сбербанк"
  },
  {
    "name": "Сириус",
    "version": "2.0.1",
    "slug": "sirius",
    "bundleId": "com.sm.FlowTime",
    "size": 397792379,
    "sizeFormatted": "379.4 МБ",
    "manifestUrl": "https://soundtrackminus-hash.github.io/ios-ota-apps-site/apps/sirius/manifest.plist",
    "downloadUrl": "https://github.com/soundtrackminus-hash/ios-ota-apps-site/releases/download/sirius-2.0.1/sirius.ipa",
    "iconUrl": "icons/hz-poster.svg",
    "searchTags": "сириус"
  },
  {
    "name": "Сияние",
    "version": "4.3.0",
    "slug": "siyanie",
    "bundleId": "am.solar.app",
    "size": 174724320,
    "sizeFormatted": "166.6 МБ",
    "manifestUrl": "https://soundtrackminus-hash.github.io/ios-ota-apps-site/apps/siyanie/manifest.plist",
    "downloadUrl": "https://github.com/soundtrackminus-hash/ios-ota-apps-site/releases/download/siyanie-4.3.0/siyanie.ipa",
    "iconUrl": "icons/hz-poster.svg",
    "searchTags": "сияние"
  },
  {
    "name": "Учим слова",
    "version": "1704",
    "slug": "uchimsya-slovam",
    "bundleId": "st.learner.main",
    "size": 285945630,
    "sizeFormatted": "272.7 МБ",
    "manifestUrl": "https://soundtrackminus-hash.github.io/ios-ota-apps-site/apps/uchimsya-slovam/manifest.plist",
    "downloadUrl": "https://github.com/soundtrackminus-hash/ios-ota-apps-site/releases/download/uchimsya-slovam-1.0.0/-.ipa",
    "iconUrl": "icons/uchimsya-slovam.png",
    "searchTags": "учим слова"
  },
  {
    "name": "ЮMoney",
    "version": "11.12.0",
    "slug": "yumoney",
    "bundleId": "ru.yoo.money",
    "size": 235264750,
    "sizeFormatted": "224.4 МБ",
    "manifestUrl": "https://soundtrackminus-hash.github.io/ios-ota-apps-site/apps/yumoney/manifest.plist",
    "downloadUrl": "https://github.com/soundtrackminus-hash/ios-ota-apps-site/releases/download/yumoney-11.12.0/yumoney.ipa",
    "iconUrl": "icons/hz-poster.svg",
    "searchTags": "юmoney"
  },
  {
    "name": "Юла",
    "version": "6.0",
    "slug": "yula",
    "bundleId": "com.allgoritm.Youla",
    "size": 137952510,
    "sizeFormatted": "131.6 МБ",
    "manifestUrl": "https://soundtrackminus-hash.github.io/ios-ota-apps-site/apps/yula/manifest.plist",
    "downloadUrl": "https://github.com/soundtrackminus-hash/ios-ota-apps-site/releases/download/yula-6.0/yula.ipa",
    "iconUrl": "icons/hz-poster.svg",
    "searchTags": "юла"
  },
  {
    "name": "Яндекс Банк",
    "version": "0.234.4",
    "slug": "yandeks-bank",
    "bundleId": "com.yandex.fintech.bank-app",
    "size": 91382008,
    "sizeFormatted": "87.1 МБ",
    "manifestUrl": "https://soundtrackminus-hash.github.io/ios-ota-apps-site/apps/yandeks-bank/manifest.plist",
    "downloadUrl": "https://github.com/soundtrackminus-hash/ios-ota-apps-site/releases/download/yandeks-bank-0.234.4/yandeks-bank.ipa",
    "iconUrl": "icons/hz-poster.svg",
    "searchTags": "яндекс банк"
  },
  {
    "name": "Яндекс Сим",
    "version": "541",
    "slug": "yandeks-sim",
    "bundleId": "ru.yandex.simapp",
    "size": 44521214,
    "sizeFormatted": "42.5 МБ",
    "manifestUrl": "https://soundtrackminus-hash.github.io/ios-ota-apps-site/apps/yandeks-sim/manifest.plist",
    "downloadUrl": "https://github.com/soundtrackminus-hash/ios-ota-apps-site/releases/download/yandeks-sim-1.7.0/yandeks-sim.ipa",
    "iconUrl": "icons/yandeks-sim.png",
    "searchTags": "яндекс сим"
  },
  {
    "name": "Календарь облако и планер",
    "version": "1.4.0",
    "slug": "kalendar-oblako-i-planer",
    "bundleId": "com.sdisk.mcd",
    "size": 61773142,
    "sizeFormatted": "58.9 МБ",
    "manifestUrl": "https://soundtrackminus-hash.github.io/ios-ota-apps-site/apps/kalendar-oblako-i-planer/manifest.plist",
    "downloadUrl": "https://github.com/soundtrackminus-hash/ios-ota-apps-site/releases/download/kalendar-oblako-i-planer-1.4.0/kalendar-oblako-i-planer.ipa",
    "iconUrl": "icons/kalendar-oblako-i-planer.png",
    "searchTags": "календарь планер напоминания"
  }
];
