// Автоматически сгенерированный список приложений
const APPS = [[
  {
    "name": "Афина бюджет",
    "version": "3",
    "slug": "afina-byudzhet-psb-bank",
    "bundleId": "com.inv.gen",
    "size": 0,
    "sizeFormatted": "Unknown",
    "manifestUrl": "https://soundtrackminus-hash.github.io/ios-ota-apps-site/apps/afina-byudzhet-psb-bank/manifest.plist",
    "downloadUrl": "https://github.com/soundtrackminus-hash/ios-ota-apps-site/releases/download/afina-byudzhet-psb-bank-1.0.0/afina-byudzhet-psb-bank.ipa",
    "iconUrl": "icons/afina-byudzhet-psb-bank.png",
    "searchTags": "afina byudzhet psb bank"
  },
  {
    "name": "Ак Барс Банк",
    "version": "4837",
    "slug": "ak-bars-onlayn",
    "bundleId": "com.inv.gen",
    "size": 0,
    "sizeFormatted": "Unknown",
    "manifestUrl": "https://soundtrackminus-hash.github.io/ios-ota-apps-site/apps/ak-bars-onlayn/manifest.plist",
    "downloadUrl": "https://github.com/soundtrackminus-hash/ios-ota-apps-site/releases/download/ak-bars-onlayn-1.0.0/ak-bars-onlayn.ipa",
    "iconUrl": "icons/ak-bars-onlayn.png",
    "searchTags": "ak bars onlayn"
  },
  {
    "name": "Anero",
    "version": "1786539266",
    "slug": "anero-ваш-онлайн-помощник-авито",
    "bundleId": "com.inv.gen",
    "size": 0,
    "sizeFormatted": "Unknown",
    "manifestUrl": "https://soundtrackminus-hash.github.io/ios-ota-apps-site/apps/anero-ваш-онлайн-помощник-авито/manifest.plist",
    "downloadUrl": "https://github.com/soundtrackminus-hash/ios-ota-apps-site/releases/download/anero-ваш-онлайн-помощник-авито-1.0.0/anero-ваш-онлайн-помощник-авито.ipa",
    "iconUrl": "icons/anero-ваш-онлайн-помощник-авито.png",
    "searchTags": "anero ваш онлайн помощник авито"
  },
  {
    "name": "ATOY",
    "version": "15",
    "slug": "atoy",
    "bundleId": "com.inv.gen",
    "size": 0,
    "sizeFormatted": "Unknown",
    "manifestUrl": "https://soundtrackminus-hash.github.io/ios-ota-apps-site/apps/atoy/manifest.plist",
    "downloadUrl": "https://github.com/soundtrackminus-hash/ios-ota-apps-site/releases/download/atoy-1.0.0/atoy.ipa",
    "iconUrl": "icons/atoy.png",
    "searchTags": "atoy"
  },
  {
    "name": "Avito (Аукцион)",
    "version": "1",
    "slug": "auktsion-au-ru-avito",
    "bundleId": "com.inv.gen",
    "size": 0,
    "sizeFormatted": "Unknown",
    "manifestUrl": "https://soundtrackminus-hash.github.io/ios-ota-apps-site/apps/auktsion-au-ru-avito/manifest.plist",
    "downloadUrl": "https://github.com/soundtrackminus-hash/ios-ota-apps-site/releases/download/auktsion-au-ru-avito-1.0.0/auktsion-au-ru-avito.ipa",
    "iconUrl": "icons/auktsion-au-ru-avito.png",
    "searchTags": "auktsion au ru avito"
  },
  {
    "name": "Без наличных",
    "version": "3.3.72",
    "slug": "bez-nalichnyh-mtc-pay",
    "bundleId": "com.inv.gen",
    "size": 0,
    "sizeFormatted": "Unknown",
    "manifestUrl": "https://soundtrackminus-hash.github.io/ios-ota-apps-site/apps/bez-nalichnyh-mtc-pay/manifest.plist",
    "downloadUrl": "https://github.com/soundtrackminus-hash/ios-ota-apps-site/releases/download/bez-nalichnyh-mtc-pay-1.0.0/bez-nalichnyh-mtc-pay.ipa",
    "iconUrl": "icons/bez-nalichnyh-mtc-pay.png",
    "searchTags": "bez nalichnyh mtc pay"
  },
  {
    "name": "Craftersy ТБАНК",
    "version": "1",
    "slug": "craftersy-tbank",
    "bundleId": "com.inv.gen",
    "size": 0,
    "sizeFormatted": "Unknown",
    "manifestUrl": "https://soundtrackminus-hash.github.io/ios-ota-apps-site/apps/craftersy-tbank/manifest.plist",
    "downloadUrl": "https://github.com/soundtrackminus-hash/ios-ota-apps-site/releases/download/craftersy-tbank-1.0.0/craftersy-tbank.ipa",
    "iconUrl": "icons/craftersy-tbank.png",
    "searchTags": "craftersy tbank"
  },
  {
    "name": "Делим Вместе Альфа-Банк",
    "version": "1",
    "slug": "delim-vmeste-alfa-bank",
    "bundleId": "com.inv.gen",
    "size": 0,
    "sizeFormatted": "Unknown",
    "manifestUrl": "https://soundtrackminus-hash.github.io/ios-ota-apps-site/apps/delim-vmeste-alfa-bank/manifest.plist",
    "downloadUrl": "https://github.com/soundtrackminus-hash/ios-ota-apps-site/releases/download/delim-vmeste-alfa-bank-1.0.0/delim-vmeste-alfa-bank.ipa",
    "iconUrl": "icons/delim-vmeste-alfa-bank.png",
    "searchTags": "delim vmeste alfa bank"
  },
  {
    "name": "До вершины (Газпромбанк)",
    "version": "1",
    "slug": "do-vershiny-5-6-0-gazprombank",
    "bundleId": "com.inv.gen",
    "size": 0,
    "sizeFormatted": "Unknown",
    "manifestUrl": "https://soundtrackminus-hash.github.io/ios-ota-apps-site/apps/do-vershiny-5-6-0-gazprombank/manifest.plist",
    "downloadUrl": "https://github.com/soundtrackminus-hash/ios-ota-apps-site/releases/download/do-vershiny-5-6-0-gazprombank-1.0.0/do-vershiny-5-6-0-gazprombank.ipa",
    "iconUrl": "icons/do-vershiny-5-6-0-gazprombank.png",
    "searchTags": "do vershiny 5 6 0 gazprombank"
  },
  {
    "name": "Дом йоги (МТС)",
    "version": "1",
    "slug": "dom-yogi-10-0-0-mtc",
    "bundleId": "com.inv.gen",
    "size": 0,
    "sizeFormatted": "Unknown",
    "manifestUrl": "https://soundtrackminus-hash.github.io/ios-ota-apps-site/apps/dom-yogi-10-0-0-mtc/manifest.plist",
    "downloadUrl": "https://github.com/soundtrackminus-hash/ios-ota-apps-site/releases/download/dom-yogi-10-0-0-mtc-1.0.0/dom-yogi-10-0-0-mtc.ipa",
    "iconUrl": "icons/dom-yogi-10-0-0-mtc.png",
    "searchTags": "dom yogi 10 0 0 mtc"
  },
  {
    "name": "FuelInTime ТБанк Инвестиции",
    "version": "1",
    "slug": "fuellntime-tbank-investitsii",
    "bundleId": "com.inv.gen",
    "size": 0,
    "sizeFormatted": "Unknown",
    "manifestUrl": "https://soundtrackminus-hash.github.io/ios-ota-apps-site/apps/fuellntime-tbank-investitsii/manifest.plist",
    "downloadUrl": "https://github.com/soundtrackminus-hash/ios-ota-apps-site/releases/download/fuellntime-tbank-investitsii-1.0.0/fuellntime-tbank-investitsii.ipa",
    "iconUrl": "icons/fuellntime-tbank-investitsii.png",
    "searchTags": "fuellntime tbank investitsii"
  },
  {
    "name": "FuellnTime ТБАНК ИНВЕСТИЦИИ",
    "version": "1.0.0",
    "slug": "fuellntime-тбанк-инвестиции",
    "bundleId": "com.inv.gen",
    "size": 0,
    "sizeFormatted": "Unknown",
    "manifestUrl": "https://soundtrackminus-hash.github.io/ios-ota-apps-site/apps/fuellntime-тбанк-инвестиции/manifest.plist",
    "downloadUrl": "https://github.com/soundtrackminus-hash/ios-ota-apps-site/releases/download/fuellntime-тбанк-инвестиции-1.0.0/fuellntime-тбанк-инвестиции.ipa",
    "iconUrl": "icons/fuellntime-тбанк-инвестиции.png",
    "searchTags": "fuellntime тбанк инвестиции"
  },
  {
    "name": "GetQuot ВТБ Инвестиции",
    "version": "1",
    "slug": "getquot-vtb-investitsii",
    "bundleId": "com.inv.gen",
    "size": 0,
    "sizeFormatted": "Unknown",
    "manifestUrl": "https://soundtrackminus-hash.github.io/ios-ota-apps-site/apps/getquot-vtb-investitsii/manifest.plist",
    "downloadUrl": "https://github.com/soundtrackminus-hash/ios-ota-apps-site/releases/download/getquot-vtb-investitsii-1.0.0/getquot-vtb-investitsii.ipa",
    "iconUrl": "icons/getquot-vtb-investitsii.png",
    "searchTags": "getquot vtb investitsii"
  },
  {
    "name": "GetQuot ВТБ ИНВЕСТИЦИИ",
    "version": "1.0.0",
    "slug": "getquot-втб-инвестиции",
    "bundleId": "com.inv.gen",
    "size": 0,
    "sizeFormatted": "Unknown",
    "manifestUrl": "https://soundtrackminus-hash.github.io/ios-ota-apps-site/apps/getquot-втб-инвестиции/manifest.plist",
    "downloadUrl": "https://github.com/soundtrackminus-hash/ios-ota-apps-site/releases/download/getquot-втб-инвестиции-1.0.0/getquot-втб-инвестиции.ipa",
    "iconUrl": "icons/getquot-втб-инвестиции.png",
    "searchTags": "getquot втб инвестиции"
  },
  {
    "name": "GTA San Andreas",
    "version": "1",
    "slug": "gta-sa-2-2-21",
    "bundleId": "com.inv.gen",
    "size": 0,
    "sizeFormatted": "Unknown",
    "manifestUrl": "https://soundtrackminus-hash.github.io/ios-ota-apps-site/apps/gta-sa-2-2-21/manifest.plist",
    "downloadUrl": "https://github.com/soundtrackminus-hash/ios-ota-apps-site/releases/download/gta-sa-2-2-21-1.0.0/gta-sa-2-2-21.ipa",
    "iconUrl": "icons/gta-sa-2-2-21.png",
    "searchTags": "gta sa 2 2 21"
  },
  {
    "name": "Happ Plus",
    "version": "2607291116",
    "slug": "happ-proxy-utility-plus",
    "bundleId": "com.inv.gen",
    "size": 0,
    "sizeFormatted": "Unknown",
    "manifestUrl": "https://soundtrackminus-hash.github.io/ios-ota-apps-site/apps/happ-proxy-utility-plus/manifest.plist",
    "downloadUrl": "https://github.com/soundtrackminus-hash/ios-ota-apps-site/releases/download/happ-proxy-utility-plus-1.0.0/happ-proxy-utility-plus.ipa",
    "iconUrl": "icons/happ-proxy-utility-plus.png",
    "searchTags": "happ proxy utility plus"
  },
  {
    "name": "iManager by INS INVEST",
    "version": "1",
    "slug": "imanager-by-ins-invest-ingossstrakh",
    "bundleId": "com.inv.gen",
    "size": 0,
    "sizeFormatted": "Unknown",
    "manifestUrl": "https://soundtrackminus-hash.github.io/ios-ota-apps-site/apps/imanager-by-ins-invest-ingossstrakh/manifest.plist",
    "downloadUrl": "https://github.com/soundtrackminus-hash/ios-ota-apps-site/releases/download/imanager-by-ins-invest-ingossstrakh-1.0.0/imanager-by-ins-invest-ingossstrakh.ipa",
    "iconUrl": "icons/imanager-by-ins-invest-ingossstrakh.png",
    "searchTags": "imanager by ins invest ingossstrakh"
  },
  {
    "name": "iManager by INS INVEST ИНГОССТРАХ",
    "version": "1.0.0",
    "slug": "imanager-by-ins-invest-ингосстрах",
    "bundleId": "com.inv.gen",
    "size": 0,
    "sizeFormatted": "Unknown",
    "manifestUrl": "https://soundtrackminus-hash.github.io/ios-ota-apps-site/apps/imanager-by-ins-invest-ингосстрах/manifest.plist",
    "downloadUrl": "https://github.com/soundtrackminus-hash/ios-ota-apps-site/releases/download/imanager-by-ins-invest-ингосстрах-1.0.0/imanager-by-ins-invest-ингосстрах.ipa",
    "iconUrl": "icons/imanager-by-ins-invest-ингосстрах.png",
    "searchTags": "imanager by ins invest ингосстрах"
  },
  {
    "name": "INCY",
    "version": "2109260730",
    "slug": "incy",
    "bundleId": "com.inv.gen",
    "size": 0,
    "sizeFormatted": "Unknown",
    "manifestUrl": "https://soundtrackminus-hash.github.io/ios-ota-apps-site/apps/incy/manifest.plist",
    "downloadUrl": "https://github.com/soundtrackminus-hash/ios-ota-apps-site/releases/download/incy-1.0.0/incy.ipa",
    "iconUrl": "icons/incy.png",
    "searchTags": "incy"
  },
  {
    "name": "Мобио Сбермобайл",
    "version": "1",
    "slug": "mobio-sbermobail",
    "bundleId": "com.inv.gen",
    "size": 0,
    "sizeFormatted": "Unknown",
    "manifestUrl": "https://soundtrackminus-hash.github.io/ios-ota-apps-site/apps/mobio-sbermobail/manifest.plist",
    "downloadUrl": "https://github.com/soundtrackminus-hash/ios-ota-apps-site/releases/download/mobio-sbermobail-1.0.0/mobio-sbermobail.ipa",
    "iconUrl": "icons/mobio-sbermobail.png",
    "searchTags": "mobio sbermobail"
  },
  {
    "name": "Notion",
    "version": "0.4.2220",
    "slug": "notion",
    "bundleId": "com.inv.gen",
    "size": 0,
    "sizeFormatted": "Unknown",
    "manifestUrl": "https://soundtrackminus-hash.github.io/ios-ota-apps-site/apps/notion/manifest.plist",
    "downloadUrl": "https://github.com/soundtrackminus-hash/ios-ota-apps-site/releases/download/notion-1.0.0/notion.ipa",
    "iconUrl": "icons/hz-poster.svg",
    "searchTags": "notion"
  },
  {
    "name": "PianoWave Премьер Кинотеатр",
    "version": "1",
    "slug": "pianowave-premer-kinoteatr",
    "bundleId": "com.inv.gen",
    "size": 0,
    "sizeFormatted": "Unknown",
    "manifestUrl": "https://soundtrackminus-hash.github.io/ios-ota-apps-site/apps/pianowave-premer-kinoteatr/manifest.plist",
    "downloadUrl": "https://github.com/soundtrackminus-hash/ios-ota-apps-site/releases/download/pianowave-premer-kinoteatr-1.0.0/pianowave-premer-kinoteatr.ipa",
    "iconUrl": "icons/pianowave-premer-kinoteatr.png",
    "searchTags": "pianowave premer kinoteatr"
  },
  {
    "name": "PianoWave ПРЕМЬЕР КИНОТЕАТР",
    "version": "1.0.0",
    "slug": "pianowave-премьер-кинотеатр",
    "bundleId": "com.inv.gen",
    "size": 0,
    "sizeFormatted": "Unknown",
    "manifestUrl": "https://soundtrackminus-hash.github.io/ios-ota-apps-site/apps/pianowave-премьер-кинотеатр/manifest.plist",
    "downloadUrl": "https://github.com/soundtrackminus-hash/ios-ota-apps-site/releases/download/pianowave-премьер-кинотеатр-1.0.0/pianowave-премьер-кинотеатр.ipa",
    "iconUrl": "icons/pianowave-премьер-кинотеатр.png",
    "searchTags": "pianowave премьер кинотеатр"
  },
  {
    "name": "SCB Notes Совкомбанк",
    "version": "1",
    "slug": "scb-notes-sovcombank",
    "bundleId": "com.inv.gen",
    "size": 0,
    "sizeFormatted": "Unknown",
    "manifestUrl": "https://soundtrackminus-hash.github.io/ios-ota-apps-site/apps/scb-notes-sovcombank/manifest.plist",
    "downloadUrl": "https://github.com/soundtrackminus-hash/ios-ota-apps-site/releases/download/scb-notes-sovcombank-1.0.0/scb-notes-sovcombank.ipa",
    "iconUrl": "icons/scb-notes-sovcombank.png",
    "searchTags": "scb notes sovcombank"
  },
  {
    "name": "SCB Notes СОВКОМБАНК",
    "version": "1.0.0",
    "slug": "scb-notes-совкомбанк",
    "bundleId": "com.inv.gen",
    "size": 0,
    "sizeFormatted": "Unknown",
    "manifestUrl": "https://soundtrackminus-hash.github.io/ios-ota-apps-site/apps/scb-notes-совкомбанк/manifest.plist",
    "downloadUrl": "https://github.com/soundtrackminus-hash/ios-ota-apps-site/releases/download/scb-notes-совкомбанк-1.0.0/scb-notes-совкомбанк.ipa",
    "iconUrl": "icons/scb-notes-совкомбанк.png",
    "searchTags": "scb notes совкомбанк"
  },
  {
    "name": "SpeakaBoo Сбер kids",
    "version": "1",
    "slug": "speakaboo-sberkids",
    "bundleId": "com.inv.gen",
    "size": 0,
    "sizeFormatted": "Unknown",
    "manifestUrl": "https://soundtrackminus-hash.github.io/ios-ota-apps-site/apps/speakaboo-sberkids/manifest.plist",
    "downloadUrl": "https://github.com/soundtrackminus-hash/ios-ota-apps-site/releases/download/speakaboo-sberkids-1.0.0/speakaboo-sberkids.ipa",
    "iconUrl": "icons/speakaboo-sberkids.png",
    "searchTags": "speakaboo sberkids"
  },
  {
    "name": "ЮMoney_11.12.0",
    "version": "1.0.0",
    "slug": "yumoney-11-12-0",
    "bundleId": "com.inv.gen",
    "size": 0,
    "sizeFormatted": "Unknown",
    "manifestUrl": "https://soundtrackminus-hash.github.io/ios-ota-apps-site/apps/yumoney-11-12-0/manifest.plist",
    "downloadUrl": "https://github.com/soundtrackminus-hash/ios-ota-apps-site/releases/download/yumoney-11-12-0-1.0.0/yumoney-11-12-0.ipa",
    "iconUrl": "icons/yumoney-11-12-0.png",
    "searchTags": "yumoney 11 12 0"
  },
  {
    "name": "СберБанк",
    "version": "17.6.1",
    "slug": "сбербанк-online",
    "bundleId": "com.inv.gen",
    "size": 532018407,
    "sizeFormatted": "507.4 МБ",
    "manifestUrl": "https://soundtrackminus-hash.github.io/ios-ota-apps-site/apps/online-com-inv-gen/manifest.plist",
    "downloadUrl": "https://github.com/soundtrackminus-hash/ios-ota-apps-site/releases/download/online-com-inv-gen-17.6.1/online-com-inv-gen.ipa",
    "iconUrl": "icons/сбербанк.png",
    "qrUrl": "icons/сбербанк-qr.png",
    "searchTags": "сбер банк онлайн"
  }
]];